services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - "${HOME}/.ollama:/root/.ollama"

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: server
    depends_on:
      - mongodb
      - ollama
    ports:
      - "8000:8000"

volumes:
  mongo-data: