apiVersion: v1
kind: Service
metadata:
  name: sample-fast-api-service
spec:
  selector:
    app: sample-fast-api
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80    # Cluster IP port
    targetPort: 5001  # Container port